### ISSUE TITLE
Create a new file for SoidaPalacios hometown

### ISSUE THREAD

**Issue by SoidaPalacios** [githubteacher/everyone-april-2016#55]
## Add file for San Diego CA
- [x] Create a branch
- [x] Add my file
- [x] Create a commit
- [x] Open a pull request
- [ ] Have a discussion about the pull request
- [ ] Merge our pull request

**Comment by yangos** [comment]
Looks good

**Comment by patray** [comment]
Nice file.

**Comment by patray** [comment]
another comment
